# Generated by Django 3.2.9 on 2021-11-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211116_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='avatar',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
