# Generated by Django 3.2.9 on 2021-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211117_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
