# Generated by Django 3.2.9 on 2021-11-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='avatar',
        ),
    ]
