# Generated by Django 3.2.9 on 2021-11-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='projects',
            new_name='project',
        ),
    ]
